#language: objective-c
#install:
#- gem install travis-xcodebuild

#script:
#- xcodebuild -project DPPickerManager.xcodeproj -scheme DPPickerManager -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

#matrix:
 # include:
  #  - os: linux
   #   dist: trusty
    #  sudo: required
     # language: cpp
   # - os: osx
    #  osx_image: xcode9
#      language: objective-c
 #     sudo: required

#script:
 # - swift build
  #- swift test

#before_install:
 # - chmod ugo+x ./Scripts/InstallSwift.sh
  #- . ./Scripts/InstallSwift.sh

#notifications:
 # email:
  #  on_success: never
   # on_failure: change
#view raw 


osx_image: xcode9
language: objective-c

before_install:
  - git submodule update --init --recursive
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

#script:
 # - rake test:ios
 # - rake test:osx
 # - rake test:xctool:ios

script:
#- xcodebuild -project DPPickerManager.xcodeproj -scheme DPPickerManager test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
-xcodebuild -project DPPickerManager.xcodeproj -scheme DPPickerManagerTests -sdk iphonesimulator -configuration Release TEST_AFTER_BUILD=YES
